language: node_js
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run build && node script.js
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
env:
  - GH_TOKEN=tataro:9a66d9fcda3eeba9e4313e55865e6e4a009aa047
